Repository Clokey-dev/clokey-server, pull requests merged in 2025-09, with the labels that each got.

#53 [feat/#52] 회원 차단 API 구현
  clokey-api/src/main/java/org/clokey/domain/member/controller/MemberController.java
  clokey-api/src/main/java/org/clokey/domain/member/exception/MemberErrorCode.java
  clokey-api/src/main/java/org/clokey/domain/member/repository/BlockRepository.java
  clokey-api/src/main/java/org/clokey/domain/member/service/MemberService.java
  clokey-api/src/main/java/org/clokey/domain/member/service/MemberServiceImpl.java
  clokey-api/src/test/java/org/clokey/domain/member/controller/MemberControllerTest.java
  clokey-api/src/test/java/org/clokey/domain/member/service/MemberServiceTest.java
  clokey-domain/src/main/java/org/clokey/member/entity/Block.java
Labels: ✨ feature

#62 [docs/#61] flyway 누락 이미지 추가
  documentation/feature/도메인 수정과 Flyway 사용법.md
Labels: 📝 documentation

#70 [fix/#69] S3 Utils 문제 & 양방향 삭제 로직 제거
  clokey-api/src/main/java/org/clokey/domain/comment/repository/ReplyRepository.java
  clokey-api/src/main/java/org/clokey/domain/comment/service/CommentServiceImpl.java
  clokey-domain/src/main/java/org/clokey/cloth/entity/Cloth.java
  clokey-domain/src/main/java/org/clokey/comment/entitiy/Comment.java
  clokey-domain/src/main/java/org/clokey/coordinate/entity/Coordinate.java
  clokey-domain/src/main/java/org/clokey/folder/entity/ClothFolder.java
  clokey-domain/src/main/java/org/clokey/folder/entity/Folder.java
  clokey-domain/src/main/java/org/clokey/history/entity/Hashtag.java
  clokey-domain/src/main/java/org/clokey/history/entity/HashtagHistory.java
  clokey-domain/src/main/java/org/clokey/history/entity/HistoryCloth.java
  clokey-domain/src/main/java/org/clokey/history/entity/HistoryImage.java
  clokey-domain/src/main/java/org/clokey/like/entity/MemberLike.java
  clokey-domain/src/main/java/org/clokey/lookbook/entity/LookBook.java
  clokey-domain/src/main/java/org/clokey/member/entity/Member.java
  clokey-domain/src/main/java/org/clokey/notification/entity/ClokeyNotification.java
  clokey-infrastructure/src/main/java/org/clokey/util/S3Util.java
  documentation/feature/도메인 수정과 Flyway 사용법.md
Labels: 🐛 fix

#73 [Feat/#72] 본인 확인 API 구현
  clokey-api/src/main/java/org/clokey/domain/member/controller/MemberController.java
  clokey-api/src/main/java/org/clokey/domain/member/dto/response/MyselfCheckResponse.java
  clokey-api/src/main/java/org/clokey/domain/member/exception/MemberErrorCode.java
  clokey-api/src/main/java/org/clokey/domain/member/service/MemberService.java
  clokey-api/src/main/java/org/clokey/domain/member/service/MemberServiceImpl.java
  clokey-api/src/test/java/org/clokey/domain/member/controller/MemberControllerTest.java
  clokey-api/src/test/java/org/clokey/domain/member/service/MemberServiceTest.java
Labels: ✨ feature
